### ISSUE TITLE
stuck in the login screen

### ISSUE THREAD

**Issue by Zfee** [GrowtopiaNoobs/GrowtopiaServer#113] opened 2018-12-22 14:20 UTC
im stuck in the login screen, i think i have evertything set up as they should, 
![image](https://user-images.githubusercontent.com/29163247/50375411-78a20d00-0605-11e9-82f7-f0be00637c3a.png)
gt v2.984

**Comment by Zfee** [comment] 2018-12-22 14:21
any ideas how to fix this?

**Comment by Mempler** [comment] 2018-12-23 10:48
Duplicate of #56

**Closed by Mempler** 2018-12-23 10:48 UTC
Labels: duplicate
