### ISSUE TITLE
How to fix Record growtopia1  to localhost already found

### ISSUE THREAD

**Issue by HelpmeHelpyous** [GrowtopiaNoobs/GrowtopiaServer#71] opened 2018-11-11 03:39 UTC
can anyone help me plsss
i ned pllsssss

**Comment by DrOreo002** [comment] 2018-11-11 04:50
delete it then from the host file

**Comment by HelpmeHelpyous** [comment] 2018-11-11 05:37
But here's what i get after i remove growtopia1 from the host file
![help](https://user-images.githubusercontent.com/44936463/48309516-f6124080-e5b6-11e8-923e-7e0a0d7421e2.PNG)

**Comment by HelpmeHelpyous** [comment] 2018-11-11 05:38
Unknown error. how to fix?

**Comment by HelpmeHelpyous** [comment] 2018-11-11 05:40
![help2](https://user-images.githubusercontent.com/44936463/48309538-615c1280-e5b7-11e8-9041-0bd275790e62.PNG)
Here's what happen when i put it back

**Comment by HelpmeHelpyous** [comment] 2018-11-11 05:41
after that, i would be stuck in logon screen...

**Comment by RU15** [comment] 2018-11-11 08:38
> after that, i would be stuck in logon screen...

You stuck in logon because you have older version of GT, when server for newer. Update your Growtopia.

**Comment by HelpmeHelpyous** [comment] 2018-11-13 09:07
I've already did, its the record growtopia1.com thing

**Comment by NotDark** [comment] 2018-11-15 14:14
your server is old

**Comment by HelpmeHelpyous** [comment] 2018-11-16 02:30
> your server is old
How do i update my server then

**Comment by learntodlgt** [comment] 2018-11-17 11:19
The thongs are v2.982 So it wont work very well

**Comment by Dunzap** [comment] 2018-11-17 14:03
So must I download the server in the newest page of wiki?

**Comment by Mempler** [comment] 2018-11-23 14:14
Duplicate of #64

**Closed by Mempler** 2018-11-23 14:14 UTC
Labels: duplicate, help wanted
