### ISSUE TITLE
[QUESTION] how to fix b1g crashing server?

### ISSUE THREAD

**Issue by noobesgt** [GrowtopiaNoobs/GrowtopiaServer#691] opened 2019-07-10 19:00 UTC
How to fix using AUX, NUL etc as name?

**Comment by moanhawks** [comment] 2019-07-10 23:27
https://github.com/GrowtopiaNoobs/GrowtopiaServer/pull/676

**Comment by noobesgt** [comment] 2019-07-11 08:15
Its not workin.

**Comment by ilyn1337** [comment] 2019-07-11 09:29
how its not working???

**Comment by noobesgt** [comment] 2019-07-11 11:01
no

**Comment by willi123yao** [comment] 2019-08-05 07:16
Like what others have mentioned, the fix for that bug is provided and if it does not seem to be working for you, please check that the fix has been properly added. Otherwise, it is another issue and not related to this and further investigation on your side is required. Once you have found the cause for the crash, please open another issue on that and we will try to help you with it.

**Closed by willi123yao** 2019-08-05 07:16 UTC
