### ISSUE TITLE
How to make an event pool?

### ISSUE THREAD

**Issue by InjectionZ** [GrowtopiaNoobs/GrowtopiaServer#851] opened 2019-09-29 00:23 UTC
Thank you :)

**Comment by MarmoriPelaa** [comment] 2019-09-30 16:11
I'll TYPE the link for a tutorial on that:
https://google.com/search?q=c%2B%2B+event+pool

**Comment by MarmoriPelaa** [comment] 2019-10-01 18:23
Since the issue isn't closed/resolved, I'll leave a question for you: What do you mean by "making an event pool" ? The question is too broad to answer. Do you need code, or maybe just help on structuring one? Please, provide us some information on what you want to achieve and what you have tried to do in order to achieve it. Also, there should be a bunch of tutorials and you can actually write your own fairly easily.

**Comment by InjectionZ** [comment] 2019-10-02 01:24
This is in the TODO list

**Comment by GrowtopiaNoobs** [comment] 2020-04-02 15:43
Closing this issue as there was no new activity.

**Closed by GrowtopiaNoobs** 2020-04-02 15:43 UTC
Labels: question
