### ISSUE TITLE
[BUG] Growtopia Crashes Upon Entering A World

### ISSUE THREAD

**Issue by WuXeR** [GrowtopiaNoobs/GrowtopiaServer#1187] opened 2020-02-13 00:36 UTC
**Describe the bug**
When I enter the world, my game just closes/crashes.

**To Reproduce**
I didn't change one bit of the code, I compiled it. Even followed the guide and I can't figure out why it's happaning.

**Expected behavior**
Obviously I should just enter the world..

**Server environment (please complete the following information):**
 - OS: Windows 10
 - Experience: Beginner
 - Modifications: None

**Client environment (please complete the following information):**
 - Growtopia version: 3.01

**Additional context**
So I think I know why growtopia crashes, this appears in the growtopia.exe log.
`Illegal item 0 in TEST
Illegal item 0 in TEST`
So I was like, okay I'll replace all tiles with 0(air) to dirt and cave bg. This is what I got,
`Illegal item 2 in TEST
Illegal item 14 in TEST`

**Comment by RajehTXD** [comment] 2020-02-13 19:54
Delete all the empty worlds. try again. dig up the source code since maybe you are clicking on the "Fake Worlds" as it states itself. Make sure you have items.dat unhash and able to get them...

**Comment by RajehTXD** [comment] 2020-02-13 19:54
> Delete all the empty worlds. try again. dig up the source code since maybe you are clicking on the "Fake Worlds" as it states itself. Make sure you have items.dat unhash and able to get them...

Hope i help.

**Comment by SecretSC** [comment] 2020-02-14 20:57
Try to delet the worlds in the worlds folder *dosent work still> same?* try update your CDNContent and type the last number 49 its the new update of gt 3.011 and done.

**Comment by Bexpg** [comment] 2020-02-15 21:03
Delete /worlds/player folder. And create new one.

**Comment by GrowtopiaNoobs** [comment] 2020-04-02 15:20
Duplicate of #1181

**Closed by GrowtopiaNoobs** 2020-04-02 15:20 UTC
Labels: bug
