### ISSUE TITLE
How Save Clothes can send me screen shot or code pls

### ISSUE THREAD

**Issue by WolfPT** [GrowtopiaNoobs/GrowtopiaServer#85] opened 2018-11-17 14:12 UTC
Can help me save cloth pls

**Comment by Dunzap** [comment] 2018-11-17 14:13
Try checking closed posts I think one of them has it (not sure)

**Comment by DrOreo002** [comment] 2018-11-18 05:31
Stop this mate, I know you really want a good Growtopia private server, but we cannot do everything for free here.

As far as I know saving clothing is kinda hard to make it to work properly. You have to learn a lot of thing such as Database management, CPP, (Database lang like JSON, MySql, etc). For those who have write access, could you please close this thanks.

**Closed** 2018-11-23 14:02 UTC
Labels: invalid

**Comment by Mempler** [comment] 2018-11-23 14:13
and btw, it's an duplicate of #66
