### ISSUE TITLE
IOS Player's Cant Login The Server Help Please.

### ISSUE THREAD

**Issue by sadMotion** [GrowtopiaNoobs/GrowtopiaServer#1234] opened 2020-03-08 06:25 UTC
IOS Player's Cant Login The Server Help Please.

**Comment by VyteGTPS** [comment] 2020-03-12 22:00
DYCK BYG

**Comment by DEERUX** [comment] 2020-03-12 22:20
lemme join the gang...
DYCK BYG

**Comment by Bexpg** [comment] 2020-03-14 16:56
delte system32222

**Comment by sadMotion** [comment] 2020-03-15 17:04
DYCK BYG

**Comment by sadMotion** [comment] 2020-03-15 17:05
> delte system32222

Omg ty fixeddd

**Comment by atomiclucky** [comment] 2020-03-15 18:46
simple fix: don't used leaked source

**Comment by Bexpg** [comment] 2020-03-17 00:36
Np

**Comment by GrowtopiaNoobs** [comment] 2020-04-02 15:18
Duplicate of #1232

**Closed by GrowtopiaNoobs** 2020-04-02 15:18 UTC
Labels: duplicate
