### ISSUE TITLE
[BUG] Server Gave 404. File not found. Bad url? 

### ISSUE THREAD

**Issue by FarhanGT** [GrowtopiaNoobs/GrowtopiaServer#1025] opened 2019-11-12 11:38 UTC
How to fix Server gave 404. File not found. Bad url?
No trolling Please🙏

**Comment by WolfPT** [comment] 2019-11-12 12:56
> How to fix Server gave 404. File not found. Bad url?
> No trolling Please

DARK#8280 add on discord.

**Comment by JadlionHD** [comment] 2019-11-12 14:07
Update your CDNContent

**Comment by WoofHax** [comment] 2019-11-12 17:08
Two ways to fix 
1. Add port 
2. You Hash dat problem

**Comment by playingo** [comment] 2019-11-12 20:11
OK GUYS THIS IS QUESTION HAS BEEN ANSWERED LIKE A MILLION TIMES ALREADY. IF YOU GOT AN ISSUE, THEN FIRST LOOK FOR OLDER THREADS THEY MAY PROVIDE THE ANSWER. STOP SPAMMING THIS GITHUB FULL OF TRASH. (written this in caps to show aggression in order to make you realize that its completely dumb what you are causing right now)

**Comment by Deveytv** [comment] 2019-11-13 07:46
Hey please, if you use this issue 404 bad url Just see the closed issue, and don't make this issue again thanks.

**Comment by IndogLelele** [comment] 2019-11-13 11:55
Update hash or using auto hash and update your cache to 24

**Comment by Grampsyyc** [comment] 2019-11-19 05:36
how do I update hash

**Comment by GrowtopiaNoobs** [comment] 2020-04-04 15:37
Duplicate of #1013

**Closed by GrowtopiaNoobs** 2020-04-04 15:37 UTC
Labels: duplicate
