### ISSUE TITLE
[BUG] Growtopia closes/crashes upon joinin world.

### ISSUE THREAD

**Issue by WuXeR** [GrowtopiaNoobs/GrowtopiaServer#1181] opened 2020-02-09 21:43 UTC
**Describe the bug**
Growtopia crashes when entering a world.

**To Reproduce**
1. Start server.
2. Open growtopia.
3. Connect without growid.
4. Join World.
5. Growtopia closes/crashes.

**Expected behavior**
I expected to enter the world.

**Server environment (please complete the following information):**
 - OS: Windows 10
 - Experience: beginner; However I'm experienced in C# & Java
 - Modifications: None

**Client environment (please complete the following information):**
 - Growtopia version: 3.01

**Comment by DrOreo002** [comment] 2020-02-09 22:03
Any error log on the console?. If theres none then might be caused by some invalid world packet, you said you know Java so maybe you can try my GrowtopiaJavaBot (Check my repos) to check for the current tank packet of world data

**Comment by WuXeR** [comment] 2020-02-09 22:19
This is the growtopia console
`Downloaded 167 bytes
Connection succeeded.
Processing connection...
We'll need to update 0 files.
Entering game...
Processing connection...
We'll need to update 0 files.
Entering game...
Canceling http...
KillCommunityHubMenu() dialog not active


Clicked button_quick_exit entity at An entity

Keyboard active: 1




Keyboard active: 0
KillCommunityHubMenu() dialog not active
KillCommunityHubMenu() dialog not active
Game menu created
Illegal item 0 in TESTING
Illegal item 0 in TESTING
Killing sound cache`

**Comment by DrOreo002** [comment] 2020-02-09 22:25
Nothing wrong with it, I'm sure its caused by invalid packet on the world. Because well this gt server is made based on gt v2, not v3

**Comment by WuXeR** [comment] 2020-02-09 22:25
Okay, so this isn't unusal? 

> Illegal item 0 in TESTING
> Illegal item 0 in TESTING

**Comment by WuXeR** [comment] 2020-02-09 23:02
I can figure out the issue..

**Comment by DrOreo002** [comment] 2020-02-10 02:41
Not sure, you may want to check the log method of the app?. And take a look at what condition its get sent

**Comment by WuXeR** [comment] 2020-02-10 03:13
thats growtopia log bruh wdym

**Comment by DrOreo002** [comment] 2020-02-10 03:14
Oh, thought it was gtserver's log 😂

**Comment by WuXeR** [comment] 2020-02-10 03:14
naa man, like I can login and everything but the moment I enter the world my game just closes

**Comment by WuXeR** [comment] 2020-02-10 03:17
I think this has to be the piece of code that crashes the game

> #ifdef TOTAL_LOG
> 	cout << "Entering a world..." << endl;
> #endif
> 	((PlayerInfo*)(peer->data))->joinClothesUpdated = false;
> 	string asdf = "0400000004A7379237BB2509E8E0EC04F8720B050000000000000000FBBB0000010000007D920100FDFDFDFD04000000040000000000000000000000070000000000"; // 0400000004A7379237BB2509E8E0EC04F8720B050000000000000000FBBB0000010000007D920100FDFDFDFD04000000040000000000000000000000080000000000000000000000000000000000000000000000000000000000000048133A0500000000BEBB0000070000000000
> 	string worldName = worldInfo->name;
> 	int xSize = worldInfo->width;
> 	int ySize = worldInfo->height;
> 	int square = xSize * ySize;
> 	__int16 nameLen = worldName.length();
> 	int payloadLen = asdf.length() / 2;
> 	int dataLen = payloadLen + 2 + nameLen + 12 + (square * 8) + 104;
> 	int allocMem = payloadLen + 2 + nameLen + 12 + (square * 8) + 104 + 16000;
> 	BYTE* data = new BYTE[allocMem];
> 	memset(data, 0, allocMem);
> 	for (int i = 0; i < asdf.length(); i += 2)
> 	{
> 		char x = ch2n(asdf[i]);
> 		x = x << 4;
> 		x += ch2n(asdf[i + 1]);
> 		memcpy(data + (i / 2), &x, 1);
> 	}
> 	int zero = 0;
> 	__int16 item = 0;
> 	int smth = 0;
> 	for (int i = 0; i < square * 8; i += 4) memcpy(data + payloadLen + i + 14 + nameLen, &zero, 4);
> 	for (int i = 0; i < square * 8; i += 8) memcpy(data + payloadLen + i + 14 + nameLen, &item, 2);
> 	memcpy(data + payloadLen, &nameLen, 2);
> 	memcpy(data + payloadLen + 2, worldName.c_str(), nameLen);
> 	memcpy(data + payloadLen + 2 + nameLen, &xSize, 4);
> 	memcpy(data + payloadLen + 6 + nameLen, &ySize, 4);
> 	memcpy(data + payloadLen + 10 + nameLen, &square, 4);
> 	BYTE* blockPtr = data + payloadLen + 14 + nameLen;
> 	for (int i = 0; i < square; i++) {
> 		if ((worldInfo->items[i].foreground == 0) || (worldInfo->items[i].foreground == 2) || (worldInfo->items[i].foreground == 8) || (worldInfo->items[i].foreground == 100)/* || (worldInfo->items[i].foreground%2)*/)
> 		{
> 			memcpy(blockPtr, &worldInfo->items[i].foreground, 2);
> 			int type = 0x00000000;
> 			// type 1 = locked
> 			if (worldInfo->items[i].water)
> 				type |= 0x04000000;
> 			if (worldInfo->items[i].glue)
> 				type |= 0x08000000;
> 			if (worldInfo->items[i].fire)
> 				type |= 0x10000000;
> 			if (worldInfo->items[i].red)
> 				type |= 0x20000000;
> 			if (worldInfo->items[i].green)
> 				type |= 0x40000000;
> 			if (worldInfo->items[i].blue)
> 				type |= 0x80000000;
> 
> 			// int type = 0x04000000; = water
> 			// int type = 0x08000000 = glue
> 			// int type = 0x10000000; = fire
> 			// int type = 0x20000000; = red color
> 			// int type = 0x40000000; = green color
> 			// int type = 0x80000000; = blue color
> 			memcpy(blockPtr + 4, &type, 4);
> 			/*if (worldInfo->items[i].foreground % 2)
> 			{
> 				blockPtr += 6;
> 			}*/
> 		}
> 		else
> 		{
> 			memcpy(blockPtr, &zero, 2);
> 		}
> 		memcpy(blockPtr + 2, &worldInfo->items[i].background, 2);
> 		blockPtr += 8;
> 		/*if (blockPtr - data < allocMem - 2000) // realloc
> 		{
> 			int wLen = blockPtr - data;
> 			BYTE* oldData = data;
> 			data = new BYTE[allocMem + 16000];
> 			memcpy(data, oldData, allocMem);
> 			allocMem += 16000;
> 			delete oldData;
> 			blockPtr = data + wLen;
> 
> 		}*/
> 	}
> 	memcpy(data + dataLen - 4, &smth, 4);
> 	ENetPacket* packet2 = enet_packet_create(data,
> 		dataLen,
> 		ENET_PACKET_FLAG_RELIABLE);
> 	enet_peer_send(peer, 0, packet2);

**Comment by DrOreo002** [comment] 2020-02-10 05:30
Maybe, I'm not sure either

**Comment by GrowtopiaNoobs** [comment] 2020-03-25 15:42
I am not sure but it might be caused by invalid `items.dat`. Where did you get that file from?

**Comment by GrowtopiaNoobs** [comment] 2020-04-14 18:37
Closing this issue as there was no new activity, so I assume it is solved.

**Closed by GrowtopiaNoobs** 2020-04-14 18:37 UTC
Labels: bug
