### ISSUE TITLE
How to Open Port

### ISSUE THREAD

**Issue by tahakocabuga** [GrowtopiaNoobs/GrowtopiaServer#702] opened 2019-07-13 10:40 UTC
How to Open Port For Everyone To Join. (I  will host in my pc system windows 10)

**Comment by herothedev** [comment] 2019-07-13 11:06
When u start server.exe and windows firewall asks things, just put all into yes. and make in run.py 127.0.0.1 to your ip.

**Comment by tahakocabuga** [comment] 2019-07-13 11:11
> When u start server.exe and windows firewall asks things, just put all into yes. and make in run.py 127.0.0.1 to your ip.

hope it work thanks

**Comment by tahakocabuga** [comment] 2019-07-13 13:06
> When u start server.exe and windows firewall asks things, just put all into yes. and make in run.py 127.0.0.1 to your ip.

it didn'T work or I can't do it

**Comment by herothedev** [comment] 2019-07-13 13:22
then something wrong with firewall.

**Comment by noobesgt** [comment] 2019-07-13 21:22
Forward ur router

**Comment by willi123yao** [comment] 2019-08-05 06:15
I would suggest you go to your router page and find how to configure port forwarding for your router online and do it from there. Don't forget to change the IP address in the python script to match your public IP (which is the IP that your players will connect to). 

Closing this issue as it seems to be resolved.

**Closed by willi123yao** 2019-08-05 06:15 UTC

**Comment by willi123yao** [comment] 2019-08-05 07:11
Duplicate of #700
