### ISSUE TITLE
How To Make Public in A VPS 

### ISSUE THREAD

**Issue by tahakocabuga** [GrowtopiaNoobs/GrowtopiaServer#703] opened 2019-07-13 16:43 UTC
Hello,

Finally I bought  a VPS and I don't know how to make public players to play. Can anyone show it in a video or photos because I need to understand :D

**Comment by flossboss** [comment] 2019-07-13 21:48
Go to firewalls, and add 2 new firewall rules:

Open port 80 UDP and port 17091 TCP. Now use the embed in wiki and just change 127.0.0.1 to your server ip. Then open run.py and your server.exe and your server should be up and running. Hope this helps

**Comment by willi123yao** [comment] 2019-08-05 07:01
I am sure there are many tutorials and documentation online for you to know how to forward those ports and open the firewall to allow players to play and join. Closing this issue as it is not directly related to the code of the server.

**Closed by willi123yao** 2019-08-05 07:01 UTC

**Comment by willi123yao** [comment] 2019-08-05 07:11
Duplicate of #700
